Repository Another-Glass/Assignment5_TEAM, pull requests merged in 2021-11, with the labels that each got.

#6 [Feat]: 상세 페이지, 목록 페이지 컨트롤러 작성
  src/controllers/trialController.js
  src/globals/responseMessage.js
Labels: :fire: Feat, :man: :computer: 준호

#7 [feat]: openApiJobs 단위테스트 추가
  src/bin/www.js
  src/jobs/openApiJobs.js
  src/package.json
  src/services/trialService.js
  src/test/data/openApiTestConfig.json
  src/test/unit/jobs/openApiJobs.test.js
Labels: :fire: Feat

#8 [Feat]: 검색 컨트롤러 추가 및 목록 페이지, 상세 페이지 수정
  src/controllers/trialController.js
  src/globals/responseMessage.js
Labels: :fire: Feat, :man: :computer: 준호

#9 [feat]: 상세 페이지, 목록 페이지 서비스 작성
  src/globals/routes.js
  src/models/index.js
  src/services/trialService.js
Labels: :fire: Feat, :man: :computer: 상수

#10 [feat]: 연구 목록 생성 API
  src/jobs/openApiJobs.js
  src/services/trialService.js
Labels: :fire: Feat, :man: :computer: 동훈, :man: :computer: 성연, :man: :computer: 현길

#12 [fix]: IS_SQLITE 변수 버그 수정, sequelize 로그 숨김
  src/jobs/openApiJobs.js
  src/models/index.js
  src/services/trialService.js
Labels: :hammer_and_wrench: Fix

#13 [docs]: README 업데이트
  README.md
Labels: :blue_book: Documentation, :man: :computer: 동훈, :man: :computer: 성연, :man: :computer: 현길

#15 [fix]: 검색 API 페이징 로직 추가
  src/services/trialService.js
Labels: :man: :computer: 상수, :hammer_and_wrench: Fix

#16 [docs]: README.md 및 trialService.js 주석 변경
  README.md
  src/services/trialService.js
Labels: :blue_book: Documentation, :man: :computer: 동훈, :man: :computer: 성연

#17 [fix]: 목록 조회 updatedAt 기준 일주일 이내 조회
  src/controllers/trialController.js
  src/package.json
  src/services/trialService.js
  src/utils/day.js
Labels: :fire: Feat, :man: :computer: 상수

#18 [feat]: 리스트 페이지 API 테스트 추가
  src/test/data/trialsData.json
  src/test/unit/controllers/trialController/getTrials.test.js
Labels: :fire: Feat, :man: :computer: 상수

#19 [feat]: 상세 페이지 API 테스트 추가
  src/controllers/trialController.js
  src/test/data/trialData.json
  src/test/unit/controllers/trialController/getTrialDetail.test.js
Labels: :fire: Feat, :man: :computer: 상수

#20 [fix]: 해쉬 버그 수정
  src/jobs/openApiJobs.js
Labels: :hammer_and_wrench: Fix

#21 [feat]: 검색 API 테스트 추가
  src/test/data/searchTrialData.json
  src/test/unit/controllers/trialController/getTrials.test.js
  src/test/unit/controllers/trialController/searchTrials.test.js
Labels: :fire: Feat, :man: :computer: 상수

#22 [docs]: README Dependencies 수정
  README.md
Labels: :blue_book: Documentation, :man: :computer: 상수
